ENV = "prod"
Debug = false
LogLevel = "info"

[HTTPClient]
Debug = false
Verbose = false
Timeout = "30s"
DialTimeout = "30s"
IdleConnTimeout = "90s"
MaxIdleConns = 500
MaxIdleConnsPerHost = 500
MaxConnsPerHost = 1000

[Database]
DBType = "postgres"
Host = "localhost"
Port = 5432
DBName = "test"
UserName = "pgsql"
PassWord = "pgsql"
CharSet = ""
LogMode = ""

[Vaccine]
BaseURL = "https://miaomiao.scmttec.com" # 基础URL
# 身份验证鉴权使用，抓包从请求头中获取
TK = ""
MemberID = "" # 接种成员id
IDCard = "" # 接种成员身份证号码
ParentCode = "51" # 某省的区域代码,四川为 51
RegionCode = "" # 选择的地区代码,4位,成都为 5101
Cookie = "" # 从 /seckill/linkman/findByUserId.do 获取
VaccineID = "" # 接种疫苗id
Total = 5  # 开启的协程数量(不建议修改，封号了我不管)
Step = 200 # 每个协程抢购时间间隔，单位毫秒(不建议修改，封号了我不管)