name: Tool Deployment

on:
  push:
    branches:
      - staging
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  test_action:
    name: test action
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: build
        run: |
          make build_linux
          ./bin/tool -h
      - name: test
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
        run: |
          go test ./...
